kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ml-mon-prometheus
  namespace: odh
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: odh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
